name: Maven Release

# i.e. uniquement lors d'un déclenchement manuel du workflow
on:
  workflow_dispatch:
    inputs:
      # Les inputs seront injectés sous forme de variable d'environnement par Github Actions
      # Le format sera normalisé : `Release version` devient `$INPUT_RELEASE_VERSION`
      # Voir https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
      Release version:
        description: 'Version to produce'
        required: true
      Dev version:
        description: 'Next SNAPSHOT version'
        required: true
        default: '1.0.1-SNAPSHOT'

env:
  MAVEN_SERVER_ID: github
  MAVEN_SERVER_LAYOUT: default
  MAVEN_SERVER_URI: https://maven.pkg.github.com/jimetevenard/java-hello-world-with-maven

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: fregante/setup-git-user@v1 # Git config user.name / user.email

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Prepare Release
      run: >
           mvn -B release:prepare
           -DreleaseVersion=$INPUT_RELEASE_VERSION
           -DdevelopmentVersion=$INPUT_DEV_VERSION
           -Dusername=$GITHUB_ACTOR
           -Dpassword=${{ secrets.GITHUB_TOKEN }}

    - name: Perform Release
      run: >
           mvn -B release:perform
           -DreleaseVersion=$INPUT_RELEASE_VERSION
           -DdevelopmentVersion=$INPUT_DEV_VERSION
           -Dusername=$GITHUB_ACTOR
           -Dpassword=${{ secrets.GITHUB_TOKEN }}
           -Darguments="
              -DaltDeploymentRepository=$MAVEN_SERVER_ID::$MAVEN_SERVER_LAYOUT::$MAVEN_SERVER_URI
              -s $GITHUB_WORKSPACE/settings.xml"
