name: Maven Release

# i.e. uniquement lors d'un déclenchement manuel du workflow
on: workflow_dispatch

# Les inputs seront injectés sous forme de variable d'environnement par Github Actions
# Le format sera normalisé : `Release version` devient `$INPUT_RELEASE_VERSION`
# Voir https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
inputs:
  Release version:
    description: 'Version to produce'
    required: true
  dev version:
    description: 'Next SNAPSHOT version'
    required: true
    default: '1.0.1-SNAPSHOT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Prepare Release
      run: >
           mvn -B release:prepare
           -DreleaseVersion=$INPUT_RELEASE_VERSION
           -DdevelopmentVersion=$INPUT_DEV_VERSION
           -Dusername=$GITHUB_ACTOR
           -Dpassword=${{ secrets.GITHUB_TOKEN }}

    - name: Perform Release
      run: >
           mvn -B release:perform
           -DreleaseVersion=$INPUT_RELEASE_VERSION
           -DdevelopmentVersion=$INPUT_DEV_VERSION
           -Dusername=$GITHUB_ACTOR
           -Dpassword=${{ secrets.GITHUB_TOKEN }}
