name: Publish Release

# Ce job se déclenche lors du push de tags de version
# Ces tags seront créés par le workflow de release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Maven Package
        run: mvn -B package -DskipTests
      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*.jar # Attachement du jar produit à la release
